// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT EDIT.

package cloudwatchiface_test

import (
	"testing"

	"github.com/bbc/mozart-api-common/Godeps/_workspace/src/github.com/aws/aws-sdk-go/service/cloudwatch"
	"github.com/bbc/mozart-api-common/Godeps/_workspace/src/github.com/aws/aws-sdk-go/service/cloudwatch/cloudwatchiface"
	"github.com/stretchr/testify/assert"
)

func TestInterface(t *testing.T) {
	assert.Implements(t, (*cloudwatchiface.CloudWatchAPI)(nil), cloudwatch.New(nil))
}
